In [1]:
import pandas as pd
import numpy as np
import plotly.express as px

In [2]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [3]:
df = pd.read_csv('Speed+Dating+Data.csv', encoding='ISO-8859-1')
df.head()

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [4]:
df.describe(include='all')

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
count,8378.000000,8377.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,8378.000000,6532.000000,8378.000000,8378.000000,8368.000000,8378.000000,8220.000000,8378.000000,8274.000000,8305.000000,8289.000000,8289.000000,8289.000000,8280.000000,8271.000000,8249.000000,8378.000000,8166.000000,8091.000000,8072.000000,8018.000000,7656.000000,7302.000000,8128.000000,8060.000000,7993.000000,8283.000000,8315,8296.000000,4914,3133,3583,8315.000000,8299.000000,8299.000000,8299,7314,4279,8299.000000,8281.000000,8299.000000,8289,8240.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8299.000000,8277.000000,1800.000000,8299.000000,8299.000000,8299.000000,8289.000000,8279.000000,8257.000000,6489.000000,6489.000000,6489.000000,6489.000000,6489.000000,6467.000000,8299.000000,8299.000000,8299.000000,8299.000000,8289.000000,8289.000000,8273.000000,8273.000000,8273.000000,8273.000000,8273.000000,4906.000000,4906.000000,4906.000000,4906.000000,4906.000000,8378.000000,8176.000000,8101.000000,8082.000000,8028.000000,7666.000000,7311.000000,8138.000000,8069.000000,8003.000000,7205.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4096.000000,4000.00000,4000.000000,4000.000000,4000.000000,4000.000000,7463.000000,7463.000000,7433.000000,1984.000000,1955.000000,1984.000000,1984.000000,1955.000000,1974.000000,7445.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.000000,5775.00000,5775.000000,5775.000000,5775.000000,5775.000000,7463.000000,7463.000000,7463.000000,7463.000000,7463.000000,4377.000000,4377.000000,4377.000000,4377.000000,4377.000000,3974.000000,3974.000000,3974.000000,1496.000000,668.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2959.000000,2016.000000,3974.000000,3974.000000,3974.000000,3974.000000,3974.000000,2016.000000,2016.000000,2016.000000,2016.000000,2016.000000
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,259,NaN,241,68,115,NaN,NaN,NaN,269,409,261,NaN,NaN,NaN,367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Business,NaN,UC Berkeley,"1,400.00","26,908.00",NaN,NaN,NaN,New York,0,"55,080.00",NaN,NaN,NaN,Finance,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,521,NaN,107,403,241,NaN,NaN,NaN,522,355,124,NaN,NaN,NaN,202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,283.675937,8.960248,0.500597,17.327166,1.828837,11.350919,16.872046,9.042731,9.295775,8.927668,8.963595,283.863767,0.164717,0.196010,0.395799,26.364999,2.756653,22.495347,17.396867,20.270759,17.459714,10.685375,11.845930,0.419551,6.190411,7.175256,7.369301,6.400599,6.778409,5.474870,6.134498,5.208251,1.960215,26.358928,NaN,7.662488,NaN,NaN,NaN,2.757186,3.784793,3.651645,NaN,NaN,NaN,2.122063,5.006762,2.158091,NaN,5.277791,6.425232,4.575491,6.245813,7.783829,6.985781,6.714544,5.737077,3.881191,5.745993,7.678515,5.304133,6.776118,7.919629,6.825401,7.851066,5.631281,4.339197,5.534131,5.570556,22.514632,17.396389,20.265613,17.457043,10.682539,11.845111,26.394360,11.071506,12.636308,15.566805,9.780089,11.014845,30.362192,13.273691,14.416891,18.422620,11.744499,11.854817,7.084733,8.294935,7.704460,8.403965,7.578388,6.941908,7.927232,8.284346,7.426213,7.617611,0.419909,6.189995,7.175164,7.368597,6.400598,6.777524,5.474559,6.134087,5.207523,0.948769,3.207814,20.791624,15.434255,17.243708,15.260869,11.144619,12.457925,7.21125,8.082000,8.257750,7.692500,7.589250,5.711510,1.843495,2.338087,32.819556,13.529923,15.293851,18.868448,7.286957,12.156028,26.217194,15.865084,17.813755,17.654765,9.913436,12.760263,26.806234,11.929177,12.103030,15.163810,9.342511,11.320866,29.344369,13.89823,13.958265,17.967233,11.909735,12.887976,7.125285,7.931529,8.238912,7.602171,7.486802,6.827964,7.394106,7.838702,7.279415,7.332191,0.780825,0.981631,0.376950,1.230615,0.934132,24.384524,16.588583,19.411346,16.233415,10.898075,12.699142,31.330357,15.654266,16.679563,16.418155,7.823909,12.207837,25.610341,10.751267,11.524839,14.276783,9.207503,11.253802,24.970936,10.923285,11.952687,14.959108,9.526191,11.966270,7.240312,8.093357,8.388777,7.658782,7.391545,6.810020,7.615079,7.932540,7.155258,7.048611
std,158.583367,5.491329,0.500029,10.940735,0.376673,5.995903,4.358458,5.514939,5.650199,5.477009,5.491068,158.584899,0.370947,0.303539,0.489051,3.563648,1.230689,12.569802,7.044003,6.782895,6.085526,6.126544,6.362746,0.493515,1.950305,1.740575,1.550501,1.954078,1.794080,2.156163,1.841258,2.129354,0.245925,3.566763,NaN,3.758935,NaN,NaN,NaN,1.230905,2.845708,2.805237,NaN,NaN,NaN,1.407181,1.444531,1.105246,NaN,3.309520,2.619024,2.801874,2.418858,1.754868,2.052232,2.263407,2.570207,2.620507,2.502218,2.006565,2.529135,2.235152,1.700927,2.156283,1.791827,2.608913,2.717612,1.734059,4.762569,12.587674,7.046700,6.783003,6.085239,6.124888,6.362154,16.297045,6.659233,6.717476,7.328256,6.998428,6.060150,16.249937,6.976775,6.263304,6.577929,6.886532,6.167314,1.395783,1.407460,1.564321,1.076608,1.778315,1.498653,1.627054,1.283657,1.779129,1.773094,0.493573,1.950169,1.740315,1.550453,1.953702,1.794055,2.156363,1.841285,2.129565,0.989889,2.444813,12.968524,6.915322,6.596420,5.356969,5.514028,5.921789,1.41545,1.455741,1.179317,1.626839,1.793136,1.820764,0.975662,0.631240,17.155270,7.977482,7.292868,8.535963,6.125187,8.241906,14.388694,6.658494,6.535894,6.129746,5.675550,6.651547,16.402836,6.401556,5.990607,7.290107,5.856329,6.296155,14.551171,6.17169,5.398621,6.100307,6.313281,5.615691,1.371390,1.503236,1.180280,1.548200,1.744634,1.411096,1.588145,1.280936,1.647478,1.521854,1.611694,1.382139,0.484683,1.294557,0.753902,13.712120,7.471537,6.124502,5.163777,5.900697,6.557041,17.551540,9.336288,7.880088,7.231325,6.100502,8.615985,17.477134,5.740351,6.004222,6.927869,6.385852,6.516178,17.007669,6.226283,7.010650,7.935509,6.403117,7.012067,1.576596,1.610309,1.459094,1.744670,1.961417,1.507341,1.504551,1.340868,1.672787,1.717988
min,1.000000,1.000000,0.000000,1.000000,1.000000,1.000000,5.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,-0.830000,0.000000,18.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,18.000000,NaN,1.000000,NaN,NaN,NaN,1.000000,0.000000,1.000000,NaN,NaN,NaN,1.000000,1.000000,1.000000,NaN,1.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,2.000000,3.000000,2.000000,2.000000,1.000000,3.000000,2.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3.000000,0.000000,0.000000,1.000000,0.000000,0.000000,3.00000,1.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,4.000000,1.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,2.000000,3.000000,2.000000,1.000000,2.000000,2.000000,4.000000,1.000000,1.000000
25%,154.000000,4.000000,0.000000,8.000000,2.000000,7.000000,14.000000,4.000000,4.000000,4.000000,4.000000,154.000000,0.000000,-0.020000,0.000000,24.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,2.000000,24.000000,NaN,5.000000,NaN,NaN,NaN,2.000000,1.000000,1.000000,NaN,NaN,NaN,1.000000,4.000000,1.000000,NaN,2.000000,4.000000,2.000000,5.000000,7.000000,6.000000,5.000000,4.000000,2.000000,4.000000,7.000000,3.000000,5.000000,7.000000,5.000000,7.000000,4.000000,2.000000,5.000000,2.000000,15.000000,15.000000,17.390000,15.000000,5.000000,9.520000,10.000000,6.000000,8.000000,10.000000,5.000000,7.000000,20.000000,10.000000,10.000000,15.000000,6.000000,10.000000,6.000000,8.000000,7.000000,8.000000,7.000000,6.000000,7.000000,8.000000,6.000000,7.000000,0.000000,5.000000,6.000000,6.000000,5.000000,6.000000,4.000000,5.000000,4.000000,0.000000,2.000000,14.810000,10.000000,10.000000,10.000000,7.000000,9.000000,7.00000,7.000000,8.000000,7.000000,7.000000,5.000000,1.000000,2.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,16.670000,10.000000,15.000000,15.000000,5.000000,10.000000,10.000000,8.000000,8.000000,9.000000,5.000000,7.000000,19.150000,10.00000,10.000000,15.000000,10.000000,10.000000,7.000000,7.000000,8.000000,7.000000,7.000000,6.000000,6.000000,7.000000,6.000000,6.000000,0.000000,0.000000,0.000000,1.000000,1.000000,15.220000,10.000000,16.670000,14.810000,5.000000,10.000000,20.000000,10.000000,10.000000,10.000000,0.000000,5.000000,10.000000,7.000000,7.000000,9.000000,5.000000,7.000000,10.000000,7.000000,7.000000,9.000000,6.000000,5.000000,7.000000,7.000000,8.000000,7.000000,6.000000,6.000000,7.000000,7.000000,6.000000,6.000000
50%,281.000000,8.000000,1.000000,16.000000,2.000000,11.000000,18.000000,8.000000,9.000000,8.000000,8.000000,281.000000,0.000000,0.210000,0.000000,26.000000,2.000000,20.000000,18.370000,20.000000,18.000000,10.000000,10.640000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,2.000000,26.000000,NaN,8.000000,NaN,NaN,NaN,2.000000,3.000000,3.000000,NaN,NaN,NaN,2.000000,5.000000,2.000000,NaN,6.000000,7.000000,4.000000,6.000000,8.000000,7.000000,7.000000,6.000000,3.000000,6.000000,8.000000,6.000000,7.000000,8.000000,7.000000,8.000000,6.000000,4.000000,6.000000,4.000000,20.000000,18.180000,20.000000,18.000000,10.000000,10.640000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.000000,15.000000,20.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,8.000000,8.000000,0.000000,6.000000,7.000000,7.000000,7.000000,7.000000,6.000000,6.000000,5.000000,0.000000,3.000000,17.650000,15.790000,18.420000,15.910000,10.000000,12.500000,7.00000,8.000000,8.000000,8.000000,8.000000,6.000000,1.000000,2.000000,30.000000,10.000000,15.000000,20.000000,5.000000,10.000000,20.000000,16.670000,19.050000,18.370000,10.000000,13.000000,25.000000,10.000000,10.000000,15.000000,10.000000,10.000000,25.000000,15.00000,15.000000,18.520000,10.000000,13.950000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000,0.000000,1.000000,0.000000,1.000000,1.000000,20.000000,16.670000,20.000000,16.330000,10.000000,14.290000,25.000000,15.000000,18.000000,17.000000,10.000000,10.000000,20.000000,10.000000,10.000000,12.000000,9.000000,10.000000,20.000000,10.000000,10.000000,15.000000,10.000000,10.000000,7.000000,8.000000,8.000000,8.000000,8.000000,7.000000,8.000000,8.000000,7.000000,7.000000
75%,407.000000,13.000000,1.000000,26.000000,2.000000,15.000000,20.000000,13.000000,14.000000,13.000000,13.000000,408.000000,0.000000,0.430000,1.000000,28.000000,4.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,28.000000,NaN,10.000000,NaN,NaN,NaN,4.000000,6.000000,6.000000,NaN,NaN,NaN,2.000000,6.000000,3.000000,NaN,7.000000,9.000000,7.000000,8.000000,9.000000,9.000000,8.000000,8.000000,6.000000,8.000000,9.000000,7.000000,9.000000,9.000000,8.000000,9.000000,8.000000,7.000000,7.000000,8.000000,25.000000,20.000000,23.810000,20.000000,15.000000,16.000000,35.000000,15.000000,16.000000,20.000000,15.000000,15.000000,40.000000,18.750000,20.000000,20.000000,15.000000,15.630000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,9.000000,9.000000,1.000000,8.000000,8.000000,8.000000,8.000000,8.000000,7.000000,7.000000,7.000000,2.000000,4.000000,25.000000,20.000000,20.000000,20.000000,15.000000,16.280000,8.00000,9.000000,9.000000,9.000000,9.000000,7.000000,3.000000,3.000000,40.000000,20.000000,20.000000,24.000000,10.000000,20.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,15.000000,15.000000,20.000000,10.000000,15.000000,38.460000,19.23000,17.390000,20.000000,15.090000,16.515000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,8.000000,9.000000,8.000000,8.000000,1.000000,1.000000,1.000000,1.000000,1.000000,30.000000,20.000000,20.000000,20.000000,15.000000,16.670000,40.000000,20.000000,20.000000,20.000000,10.000000,20.000000,37.000000,15.000000,15.000000,20.000000,10.000000,15.000000,35.000000,15.000000,15.000000,20.000000,10.000000,15.000000,8.000000,9.000000,9.000000,9.000000,9.000000,8.000000,9.000000,9.000000,8.000000,8.000000
max,552.000000,22.000000,1.000000,44.000000,2.000000,21.000000,22.000000,22.000000,22.000000,22.000000,22.000000,552.000000,1.000000,0.910000,1.000000,55.000000,6.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,1.000000,10.500000,10.000000,10.000000,11.000000,10.000000,10.000000,10.000000,10.000000,8.000000,55.000000,NaN,18.000000,NaN,NaN,NaN,6.000000,10.000000,10.000000,NaN,NaN,NaN,6.000000,7.000000,7.000000,NaN,17.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,14.000000,10.000000,13.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,20.000000,100.000000,60.000000,50.000000,50.000000,53.000000,30.000000,95.000000,35.000000,35.000000,45.000000,50.000000,40.000000,100.000000,50.000000,40.000000,50.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,1.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,8.000000,18.000000,95.000000,50.000000,40.000000,40.000000,23.810000,30.000000,10.00000,10.000000,10.000000,10.000000,10.000000,10.000000,3.000000,3.000000,80.000000,40.000000,50.000000,50.000000,20.000000,40.000000,85.000000,50.000000,40.000000,50.000000,22.220000,35.000000,100.000000,35.000000,40.000000,50.000000,35.000000,40.000000,85.000000,40.00000,30.770000,40.000000,50.000000,30.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,10.000000,21.000000,9.000000,1.000000,9.000000,4.000000,80.000000,65.000000,45.000000,30.000000,30.000000,55.000000,80.000000,60.000000,45.000000,40.000000,30.000000,55.000000,80.000000,40.000000,30.000000,30.000000,40.000000,45.000000,80.000000,50.000000,60.000000,40.000000,50.000000,45.000000,12.000000,12.000000,12.000000,12.000000,12.000000,10.000000,10.000000,10.000000,10.000000,10.000000

In [5]:
print(df.shape)
print(df.info(verbose=True, show_counts=True))

(8378, 195)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 195 columns):
 #    Column    Non-Null Count  Dtype
---   ------    --------------  -----
 0    iid       8378 non-null   int64
 1    id        8377 non-null   float64
 2    gender    8378 non-null   int64
 3    idg       8378 non-null   int64
 4    condtn    8378 non-null   int64
 5    wave      8378 non-null   int64
 6    round     8378 non-null   int64
 7    position  8378 non-null   int64
 8    positin1  6532 non-null   float64
 9    order     8378 non-null   int64
 10   partner   8378 non-null   int64
 11   pid       8368 non-null   float64
 12   match     8378 non-null   int64
 13   int_corr  8220 non-null   float64
 14   samerace  8378 non-null   int64
 15   age_o     8274 non-null   float64
 16   race_o    8305 non-null   float64
 17   pf_o_att  8289 non-null   float64
 18   pf_o_sin  8289 non-null   float64
 19   pf_o_int  8289 non-null   float64
 20   pf_o_fun  8280 non-null   float64
 21   pf_o_amb  8271 non-null   float64
 22   pf_o_sha  8249 non-null   float64
 23   dec_o     8378 non-null   int64
 24   attr_o    8166 non-null   float64
 25   sinc_o    8091 non-null   float64
 26   intel_o   8072 non-null   float64
 27   fun_o     8018 non-null   float64
 28   amb_o     7656 non-null   float64
 29   shar_o    7302 non-null   float64
 30   like_o    8128 non-null   float64
 31   prob_o    8060 non-null   float64
 32   met_o     7993 non-null   float64
 33   age       8283 non-null   float64
 34   field     8315 non-null   object
 35   field_cd  8296 non-null   float64
 36   undergra  4914 non-null   object
 37   mn_sat    3133 non-null   object
 38   tuition   3583 non-null   object
 39   race      8315 non-null   float64
 40   imprace   8299 non-null   float64
 41   imprelig  8299 non-null   float64
 42   from      8299 non-null   object
 43   zipcode   7314 non-null   object
 44   income    4279 non-null   object
 45   goal      8299 non-null   float64
 46   date      8281 non-null   float64
 47   go_out    8299 non-null   float64
 48   career    8289 non-null   object
 49   career_c  8240 non-null   float64
 50   sports    8299 non-null   float64
 51   tvsports  8299 non-null   float64
 52   exercise  8299 non-null   float64
 53   dining    8299 non-null   float64
 54   museums   8299 non-null   float64
 55   art       8299 non-null   float64
 56   hiking    8299 non-null   float64
 57   gaming    8299 non-null   float64
 58   clubbing  8299 non-null   float64
 59   reading   8299 non-null   float64
 60   tv        8299 non-null   float64
 61   theater   8299 non-null   float64
 62   movies    8299 non-null   float64
 63   concerts  8299 non-null   float64
 64   music     8299 non-null   float64
 65   shopping  8299 non-null   float64
 66   yoga      8299 non-null   float64
 67   exphappy  8277 non-null   float64
 68   expnum    1800 non-null   float64
 69   attr1_1   8299 non-null   float64
 70   sinc1_1   8299 non-null   float64
 71   intel1_1  8299 non-null   float64
 72   fun1_1    8289 non-null   float64
 73   amb1_1    8279 non-null   float64
 74   shar1_1   8257 non-null   float64
 75   attr4_1   6489 non-null   float64
 76   sinc4_1   6489 non-null   float64
 77   intel4_1  6489 non-null   float64
 78   fun4_1    6489 non-null   float64
 79   amb4_1    6489 non-null   float64
 80   shar4_1   6467 non-null   float64
 81   attr2_1   8299 non-null   float64
 82   sinc2_1   8299 non-null   float64
 83   intel2_1  8299 non-null   float64
 84   fun2_1    8299 non-null   float64
 85   amb2_1    8289 non-null   float64
 86   shar2_1   8289 non-null   float64
 87   attr3_1   8273 non-null   float64
 88   sinc3_1   8273 non-null   float64
 89   fun3_1    8273 non-null   float64
 90   intel3_1  8273 non-null   float64
 91   amb3_1    8273 non-null   float64
 92   attr5_1   4906 non-null   float64
 93   sinc5_1   4906 non-null   float64
 94   intel5_1  4906 non-null   float64
 95   fun5_1    4906 non-null   float64
 96   amb5_1    4906 non-null   float64
 97   dec       8378 non-null   int64
 98   attr      8176 non-null   float64
 99   sinc      8101 non-null   float64
 100  intel     8082 non-null   float64
 101  fun       8028 non-null   float64
 102  amb       7666 non-null   float64
 103  shar      7311 non-null   float64
 104  like      8138 non-null   float64
 105  prob      8069 non-null   float64
 106  met       8003 non-null   float64
 107  match_es  7205 non-null   float64
 108  attr1_s   4096 non-null   float64
 109  sinc1_s   4096 non-null   float64
 110  intel1_s  4096 non-null   float64
 111  fun1_s    4096 non-null   float64
 112  amb1_s    4096 non-null   float64
 113  shar1_s   4096 non-null   float64
 114  attr3_s   4000 non-null   float64
 115  sinc3_s   4000 non-null   float64
 116  intel3_s  4000 non-null   float64
 117  fun3_s    4000 non-null   float64
 118  amb3_s    4000 non-null   float64
 119  satis_2   7463 non-null   float64
 120  length    7463 non-null   float64
 121  numdat_2  7433 non-null   float64
 122  attr7_2   1984 non-null   float64
 123  sinc7_2   1955 non-null   float64
 124  intel7_2  1984 non-null   float64
 125  fun7_2    1984 non-null   float64
 126  amb7_2    1955 non-null   float64
 127  shar7_2   1974 non-null   float64
 128  attr1_2   7445 non-null   float64
 129  sinc1_2   7463 non-null   float64
 130  intel1_2  7463 non-null   float64
 131  fun1_2    7463 non-null   float64
 132  amb1_2    7463 non-null   float64
 133  shar1_2   7463 non-null   float64
 134  attr4_2   5775 non-null   float64
 135  sinc4_2   5775 non-null   float64
 136  intel4_2  5775 non-null   float64
 137  fun4_2    5775 non-null   float64
 138  amb4_2    5775 non-null   float64
 139  shar4_2   5775 non-null   float64
 140  attr2_2   5775 non-null   float64
 141  sinc2_2   5775 non-null   float64
 142  intel2_2  5775 non-null   float64
 143  fun2_2    5775 non-null   float64
 144  amb2_2    5775 non-null   float64
 145  shar2_2   5775 non-null   float64
 146  attr3_2   7463 non-null   float64
 147  sinc3_2   7463 non-null   float64
 148  intel3_2  7463 non-null   float64
 149  fun3_2    7463 non-null   float64
 150  amb3_2    7463 non-null   float64
 151  attr5_2   4377 non-null   float64
 152  sinc5_2   4377 non-null   float64
 153  intel5_2  4377 non-null   float64
 154  fun5_2    4377 non-null   float64
 155  amb5_2    4377 non-null   float64
 156  you_call  3974 non-null   float64
 157  them_cal  3974 non-null   float64
 158  date_3    3974 non-null   float64
 159  numdat_3  1496 non-null   float64
 160  num_in_3  668 non-null    float64
 161  attr1_3   3974 non-null   float64
 162  sinc1_3   3974 non-null   float64
 163  intel1_3  3974 non-null   float64
 164  fun1_3    3974 non-null   float64
 165  amb1_3    3974 non-null   float64
 166  shar1_3   3974 non-null   float64
 167  attr7_3   2016 non-null   float64
 168  sinc7_3   2016 non-null   float64
 169  intel7_3  2016 non-null   float64
 170  fun7_3    2016 non-null   float64
 171  amb7_3    2016 non-null   float64
 172  shar7_3   2016 non-null   float64
 173  attr4_3   2959 non-null   float64
 174  sinc4_3   2959 non-null   float64
 175  intel4_3  2959 non-null   float64
 176  fun4_3    2959 non-null   float64
 177  amb4_3    2959 non-null   float64
 178  shar4_3   2959 non-null   float64
 179  attr2_3   2959 non-null   float64
 180  sinc2_3   2959 non-null   float64
 181  intel2_3  2959 non-null   float64
 182  fun2_3    2959 non-null   float64
 183  amb2_3    2959 non-null   float64
 184  shar2_3   2016 non-null   float64
 185  attr3_3   3974 non-null   float64
 186  sinc3_3   3974 non-null   float64
 187  intel3_3  3974 non-null   float64
 188  fun3_3    3974 non-null   float64
 189  amb3_3    3974 non-null   float64
 190  attr5_3   2016 non-null   float64
 191  sinc5_3   2016 non-null   float64
 192  intel5_3  2016 non-null   float64
 193  fun5_3    2016 non-null   float64
 194  amb5_3    2016 non-null   float64
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB
None

In [10]:
# Handle income as float
df['income'] = df['income'].str.replace(',', '')
df['income'] = df['income'].astype(float)

In [ ]:
columns = df.columns[df.isna().any()].tolist()
columns_and_types = {}

for column in columns:
    columns_and_types[column] = str(df.dtypes[column])

columns_and_types

{'id': 'float64',
 'positin1': 'float64',
 'pid': 'float64',
 'int_corr': 'float64',
 'age_o': 'float64',
 'race_o': 'float64',
 'pf_o_att': 'float64',
 'pf_o_sin': 'float64',
 'pf_o_int': 'float64',
 'pf_o_fun': 'float64',
 'pf_o_amb': 'float64',
 'pf_o_sha': 'float64',
 'attr_o': 'float64',
 'sinc_o': 'float64',
 'intel_o': 'float64',
 'fun_o': 'float64',
 'amb_o': 'float64',
 'shar_o': 'float64',
 'like_o': 'float64',
 'prob_o': 'float64',
 'met_o': 'float64',
 'age': 'float64',
 'field': 'object',
 'field_cd': 'float64',
 'undergra': 'object',
 'mn_sat': 'object',
 'tuition': 'object',
 'race': 'float64',
 'imprace': 'float64',
 'imprelig': 'float64',
 'from': 'object',
 'zipcode': 'object',
 'income': 'object',
 'goal': 'float64',
 'date': 'float64',
 'go_out': 'float64',
 'career': 'object',
 'career_c': 'float64',
 'sports': 'float64',
 'tvsports': 'float64',
 'exercise': 'float64',
 'dining': 'float64',
 'museums': 'float64',
 'art': 'float64',
 'hiking': 'float64',
 'gaming': 'float64',
 'clubbing': 'float64',
 'reading': 'float64',
 'tv': 'float64',
 'theater': 'float64',
 'movies': 'float64',
 'concerts': 'float64',
 'music': 'float64',
 'shopping': 'float64',
 'yoga': 'float64',
 'exphappy': 'float64',
 'expnum': 'float64',
 'attr1_1': 'float64',
 'sinc1_1': 'float64',
 'intel1_1': 'float64',
 'fun1_1': 'float64',
 'amb1_1': 'float64',
 'shar1_1': 'float64',
 'attr4_1': 'float64',
 'sinc4_1': 'float64',
 'intel4_1': 'float64',
 'fun4_1': 'float64',
 'amb4_1': 'float64',
 'shar4_1': 'float64',
 'attr2_1': 'float64',
 'sinc2_1': 'float64',
 'intel2_1': 'float64',
 'fun2_1': 'float64',
 'amb2_1': 'float64',
 'shar2_1': 'float64',
 'attr3_1': 'float64',
 'sinc3_1': 'float64',
 'fun3_1': 'float64',
 'intel3_1': 'float64',
 'amb3_1': 'float64',
 'attr5_1': 'float64',
 'sinc5_1': 'float64',
 'intel5_1': 'float64',
 'fun5_1': 'float64',
 'amb5_1': 'float64',
 'attr': 'float64',
 'sinc': 'float64',
 'intel': 'float64',
 'fun': 'float64',
 'amb': 'float64',
 'shar': 'float64',
 'like': 'float64',
 'prob': 'float64',
 'met': 'float64',
 'match_es': 'float64',
 'attr1_s': 'float64',
 'sinc1_s': 'float64',
 'intel1_s': 'float64',
 'fun1_s': 'float64',
 'amb1_s': 'float64',
 'shar1_s': 'float64',
 'attr3_s': 'float64',
 'sinc3_s': 'float64',
 'intel3_s': 'float64',
 'fun3_s': 'float64',
 'amb3_s': 'float64',
 'satis_2': 'float64',
 'length': 'float64',
 'numdat_2': 'float64',
 'attr7_2': 'float64',
 'sinc7_2': 'float64',
 'intel7_2': 'float64',
 'fun7_2': 'float64',
 'amb7_2': 'float64',
 'shar7_2': 'float64',
 'attr1_2': 'float64',
 'sinc1_2': 'float64',
 'intel1_2': 'float64',
 'fun1_2': 'float64',
 'amb1_2': 'float64',
 'shar1_2': 'float64',
 'attr4_2': 'float64',
 'sinc4_2': 'float64',
 'intel4_2': 'float64',
 'fun4_2': 'float64',
 'amb4_2': 'float64',
 'shar4_2': 'float64',
 'attr2_2': 'float64',
 'sinc2_2': 'float64',
 'intel2_2': 'float64',
 'fun2_2': 'float64',
 'amb2_2': 'float64',
 'shar2_2': 'float64',
 'attr3_2': 'float64',
 'sinc3_2': 'float64',
 'intel3_2': 'float64',
 'fun3_2': 'float64',
 'amb3_2': 'float64',
 'attr5_2': 'float64',
 'sinc5_2': 'float64',
 'intel5_2': 'float64',
 'fun5_2': 'float64',
 'amb5_2': 'float64',
 'you_call': 'float64',
 'them_cal': 'float64',
 'date_3': 'float64',
 'numdat_3': 'float64',
 'num_in_3': 'float64',
 'attr1_3': 'float64',
 'sinc1_3': 'float64',
 'intel1_3': 'float64',
 'fun1_3': 'float64',
 'amb1_3': 'float64',
 'shar1_3': 'float64',
 'attr7_3': 'float64',
 'sinc7_3': 'float64',
 'intel7_3': 'float64',
 'fun7_3': 'float64',
 'amb7_3': 'float64',
 'shar7_3': 'float64',
 'attr4_3': 'float64',
 'sinc4_3': 'float64',
 'intel4_3': 'float64',
 'fun4_3': 'float64',
 'amb4_3': 'float64',
 'shar4_3': 'float64',
 'attr2_3': 'float64',
 'sinc2_3': 'float64',
 'intel2_3': 'float64',
 'fun2_3': 'float64',
 'amb2_3': 'float64',
 'shar2_3': 'float64',
 'attr3_3': 'float64',
 'sinc3_3': 'float64',
 'intel3_3': 'float64',
 'fun3_3': 'float64',
 'amb3_3': 'float64',
 'attr5_3': 'float64',
 'sinc5_3': 'float64',
 'intel5_3': 'float64',
 'fun5_3': 'float64',
 'amb5_3': 'float64'}

1. Handling "Unknown" Columns (positin1)
Validation: You are correct to be suspicious of positin1. However, looking at the dataset documentation, positin1 is actually a valid column (likely a typo in the original dataset for "position at start"). Data documentation says: "positin1: station number where started".
Logic: treating it as "Unknown" is safe if you don't use it, but be aware it does have a meaning.
2. The "100 vs 10" Scale Issue
Critical: You correctly identified that attr1_1 through amb1_1 (and similar waves) use different scales (100-point allocation vs 1-10 rating).
Flaw in current logic: If you impute the mean before fixing this, you will corrupt the data. The mean of a 100-point scale column will be massively higher than the 1-10 scale values.
Fix: You must normalize these columns to a common scale (e.g., convert everything to percentage or a 1-10 scale) before calculating the mean or imputing values.
3. Imputing age_o and race_o
Great intuition: Your idea to "get the real age in other rows" is excellent and the best approach.
Why: Every partner (pid) is also a participant (iid) in another row. You can create a look-up table (dictionary) mapping iid -> age and iid -> race from the dataset itself. Use this to fill in missing age_o and race_o based on pid instead of using a generic mean.
4. fillna("Unknown") for Object Columns
Risk: be careful with columns like income. In the dataframe preview, income looks like "69,487.00". Pandas sees this as an "object" (string) because of the comma.
Improvement: If you fill "Unknown" now, you can't convert it to a number later. You should clean these specific columns (remove commas, convert to float) first, and then use numeric imputation (like median) instead of "Unknown".
5. fillna(int(mean)) for All Other Columns
Risk 1 (Categorical Codes): Columns like field_cd, career_c, race, and date are "categorical" but encoded as numbers.
Example: race 1=Black, 2=White, 3=Latino. If you have a missing race and impute the mean (e.g., 2.4), and cast to integer (2), you are forcing everyone to be "White" just because of the math.
Better approach: Use the Mode (most frequent value) or a distinct "Unknown" code (like -1) for categorical codes.
Risk 2 (Integer Casting): Casting the mean to int throws away precision for continuous variables (like ratings attr_o). A rating of 7.5 is meaningful; rounding it to 7 loses signal.
Summary
Your logic to check documentation is spot on. The main improvements needed are:

Clean data types first (fix income).

In [ ]:
# Fill NA
# To improve :
# For the attributes: Quite tricky because on certain waves, it is not on 100 but on 10
# For "age_o" & "race_o": Try to get the real age in other rows and then assign it
unknown_columns = ['id', 'positin1', 'pid']
df_cleaned = df.copy()
#print(df_cleaned.shape)

for i in columns_and_types:
    #print(i, columns_and_types[i])
    if i in unknown_columns or columns_and_types[i] == "object":
        df_cleaned[i].fillna("Unknown")
    else:
        print(i)
        df_cleaned[i].fillna(int(df_cleaned[i].mean()))

#print(df_cleaned.shape)
print(df_cleaned.info(verbose=True, show_counts=True))

int_corr
age_o
race_o
pf_o_att
pf_o_sin
pf_o_int
pf_o_fun
pf_o_amb
pf_o_sha
attr_o
sinc_o
intel_o
fun_o
amb_o
shar_o
like_o
prob_o
met_o
age
field_cd
race
imprace
imprelig
goal
date
go_out
career_c
sports
tvsports
exercise
dining
museums
art
hiking
gaming
clubbing
reading
tv
theater
movies
concerts
music
shopping
yoga
exphappy
expnum
attr1_1
sinc1_1
intel1_1
fun1_1
amb1_1
shar1_1
attr4_1
sinc4_1
intel4_1
fun4_1
amb4_1
shar4_1
attr2_1
sinc2_1
intel2_1
fun2_1
amb2_1
shar2_1
attr3_1
sinc3_1
fun3_1
intel3_1
amb3_1
attr5_1
sinc5_1
intel5_1
fun5_1
amb5_1
attr
sinc
intel
fun
amb
shar
like
prob
met
match_es
attr1_s
sinc1_s
intel1_s
fun1_s
amb1_s
shar1_s
attr3_s
sinc3_s
intel3_s
fun3_s
amb3_s
satis_2
length
numdat_2
attr7_2
sinc7_2
intel7_2
fun7_2
amb7_2
shar7_2
attr1_2
sinc1_2
intel1_2
fun1_2
amb1_2
shar1_2
attr4_2
sinc4_2
intel4_2
fun4_2
amb4_2
shar4_2
attr2_2
sinc2_2
intel2_2
fun2_2
amb2_2
shar2_2
attr3_2
sinc3_2
intel3_2
fun3_2
amb3_2
attr5_2
sinc5_2
intel5_2
fun5_2
amb5_2
you_call
them_cal
date_3
numdat_3
num_in_3
attr1_3
sinc1_3
intel1_3
fun1_3
amb1_3
shar1_3
attr7_3
sinc7_3
intel7_3
fun7_3
amb7_3
shar7_3
attr4_3
sinc4_3
intel4_3
fun4_3
amb4_3
shar4_3
attr2_3
sinc2_3
intel2_3
fun2_3
amb2_3
shar2_3
attr3_3
sinc3_3
intel3_3
fun3_3
amb3_3
attr5_3
sinc5_3
intel5_3
fun5_3
amb5_3
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 195 columns):
 #    Column    Non-Null Count  Dtype
---   ------    --------------  -----
 0    iid       8378 non-null   int64
 1    id        8377 non-null   float64
 2    gender    8378 non-null   int64
 3    idg       8378 non-null   int64
 4    condtn    8378 non-null   int64
 5    wave      8378 non-null   int64
 6    round     8378 non-null   int64
 7    position  8378 non-null   int64
 8    positin1  6532 non-null   float64
 9    order     8378 non-null   int64
 10   partner   8378 non-null   int64
 11   pid       8368 non-null   float64
 12   match     8378 non-null   int64
 13   int_corr  8220 non-null   float64
 14   samerace  8378 non-null   int64
 15   age_o     8274 non-null   float64
 16   race_o    8305 non-null   float64
 17   pf_o_att  8289 non-null   float64
 18   pf_o_sin  8289 non-null   float64
 19   pf_o_int  8289 non-null   float64
 20   pf_o_fun  8280 non-null   float64
 21   pf_o_amb  8271 non-null   float64
 22   pf_o_sha  8249 non-null   float64
 23   dec_o     8378 non-null   int64
 24   attr_o    8166 non-null   float64
 25   sinc_o    8091 non-null   float64
 26   intel_o   8072 non-null   float64
 27   fun_o     8018 non-null   float64
 28   amb_o     7656 non-null   float64
 29   shar_o    7302 non-null   float64
 30   like_o    8128 non-null   float64
 31   prob_o    8060 non-null   float64
 32   met_o     7993 non-null   float64
 33   age       8283 non-null   float64
 34   field     8315 non-null   object
 35   field_cd  8296 non-null   float64
 36   undergra  4914 non-null   object
 37   mn_sat    3133 non-null   object
 38   tuition   3583 non-null   object
 39   race      8315 non-null   float64
 40   imprace   8299 non-null   float64
 41   imprelig  8299 non-null   float64
 42   from      8299 non-null   object
 43   zipcode   7314 non-null   object
 44   income    4279 non-null   object
 45   goal      8299 non-null   float64
 46   date      8281 non-null   float64
 47   go_out    8299 non-null   float64
 48   career    8289 non-null   object
 49   career_c  8240 non-null   float64
 50   sports    8299 non-null   float64
 51   tvsports  8299 non-null   float64
 52   exercise  8299 non-null   float64
 53   dining    8299 non-null   float64
 54   museums   8299 non-null   float64
 55   art       8299 non-null   float64
 56   hiking    8299 non-null   float64
 57   gaming    8299 non-null   float64
 58   clubbing  8299 non-null   float64
 59   reading   8299 non-null   float64
 60   tv        8299 non-null   float64
 61   theater   8299 non-null   float64
 62   movies    8299 non-null   float64
 63   concerts  8299 non-null   float64
 64   music     8299 non-null   float64
 65   shopping  8299 non-null   float64
 66   yoga      8299 non-null   float64
 67   exphappy  8277 non-null   float64
 68   expnum    1800 non-null   float64
 69   attr1_1   8299 non-null   float64
 70   sinc1_1   8299 non-null   float64
 71   intel1_1  8299 non-null   float64
 72   fun1_1    8289 non-null   float64
 73   amb1_1    8279 non-null   float64
 74   shar1_1   8257 non-null   float64
 75   attr4_1   6489 non-null   float64
 76   sinc4_1   6489 non-null   float64
 77   intel4_1  6489 non-null   float64
 78   fun4_1    6489 non-null   float64
 79   amb4_1    6489 non-null   float64
 80   shar4_1   6467 non-null   float64
 81   attr2_1   8299 non-null   float64
 82   sinc2_1   8299 non-null   float64
 83   intel2_1  8299 non-null   float64
 84   fun2_1    8299 non-null   float64
 85   amb2_1    8289 non-null   float64
 86   shar2_1   8289 non-null   float64
 87   attr3_1   8273 non-null   float64
 88   sinc3_1   8273 non-null   float64
 89   fun3_1    8273 non-null   float64
 90   intel3_1  8273 non-null   float64
 91   amb3_1    8273 non-null   float64
 92   attr5_1   4906 non-null   float64
 93   sinc5_1   4906 non-null   float64
 94   intel5_1  4906 non-null   float64
 95   fun5_1    4906 non-null   float64
 96   amb5_1    4906 non-null   float64
 97   dec       8378 non-null   int64
 98   attr      8176 non-null   float64
 99   sinc      8101 non-null   float64
 100  intel     8082 non-null   float64
 101  fun       8028 non-null   float64
 102  amb       7666 non-null   float64
 103  shar      7311 non-null   float64
 104  like      8138 non-null   float64
 105  prob      8069 non-null   float64
 106  met       8003 non-null   float64
 107  match_es  7205 non-null   float64
 108  attr1_s   4096 non-null   float64
 109  sinc1_s   4096 non-null   float64
 110  intel1_s  4096 non-null   float64
 111  fun1_s    4096 non-null   float64
 112  amb1_s    4096 non-null   float64
 113  shar1_s   4096 non-null   float64
 114  attr3_s   4000 non-null   float64
 115  sinc3_s   4000 non-null   float64
 116  intel3_s  4000 non-null   float64
 117  fun3_s    4000 non-null   float64
 118  amb3_s    4000 non-null   float64
 119  satis_2   7463 non-null   float64
 120  length    7463 non-null   float64
 121  numdat_2  7433 non-null   float64
 122  attr7_2   1984 non-null   float64
 123  sinc7_2   1955 non-null   float64
 124  intel7_2  1984 non-null   float64
 125  fun7_2    1984 non-null   float64
 126  amb7_2    1955 non-null   float64
 127  shar7_2   1974 non-null   float64
 128  attr1_2   7445 non-null   float64
 129  sinc1_2   7463 non-null   float64
 130  intel1_2  7463 non-null   float64
 131  fun1_2    7463 non-null   float64
 132  amb1_2    7463 non-null   float64
 133  shar1_2   7463 non-null   float64
 134  attr4_2   5775 non-null   float64
 135  sinc4_2   5775 non-null   float64
 136  intel4_2  5775 non-null   float64
 137  fun4_2    5775 non-null   float64
 138  amb4_2    5775 non-null   float64
 139  shar4_2   5775 non-null   float64
 140  attr2_2   5775 non-null   float64
 141  sinc2_2   5775 non-null   float64
 142  intel2_2  5775 non-null   float64
 143  fun2_2    5775 non-null   float64
 144  amb2_2    5775 non-null   float64
 145  shar2_2   5775 non-null   float64
 146  attr3_2   7463 non-null   float64
 147  sinc3_2   7463 non-null   float64
 148  intel3_2  7463 non-null   float64
 149  fun3_2    7463 non-null   float64
 150  amb3_2    7463 non-null   float64
 151  attr5_2   4377 non-null   float64
 152  sinc5_2   4377 non-null   float64
 153  intel5_2  4377 non-null   float64
 154  fun5_2    4377 non-null   float64
 155  amb5_2    4377 non-null   float64
 156  you_call  3974 non-null   float64
 157  them_cal  3974 non-null   float64
 158  date_3    3974 non-null   float64
 159  numdat_3  1496 non-null   float64
 160  num_in_3  668 non-null    float64
 161  attr1_3   3974 non-null   float64
 162  sinc1_3   3974 non-null   float64
 163  intel1_3  3974 non-null   float64
 164  fun1_3    3974 non-null   float64
 165  amb1_3    3974 non-null   float64
 166  shar1_3   3974 non-null   float64
 167  attr7_3   2016 non-null   float64
 168  sinc7_3   2016 non-null   float64
 169  intel7_3  2016 non-null   float64
 170  fun7_3    2016 non-null   float64
 171  amb7_3    2016 non-null   float64
 172  shar7_3   2016 non-null   float64
 173  attr4_3   2959 non-null   float64
 174  sinc4_3   2959 non-null   float64
 175  intel4_3  2959 non-null   float64
 176  fun4_3    2959 non-null   float64
 177  amb4_3    2959 non-null   float64
 178  shar4_3   2959 non-null   float64
 179  attr2_3   2959 non-null   float64
 180  sinc2_3   2959 non-null   float64
 181  intel2_3  2959 non-null   float64
 182  fun2_3    2959 non-null   float64
 183  amb2_3    2959 non-null   float64
 184  shar2_3   2016 non-null   float64
 185  attr3_3   3974 non-null   float64
 186  sinc3_3   3974 non-null   float64
 187  intel3_3  3974 non-null   float64
 188  fun3_3    3974 non-null   float64
 189  amb3_3    3974 non-null   float64
 190  attr5_3   2016 non-null   float64
 191  sinc5_3   2016 non-null   float64
 192  intel5_3  2016 non-null   float64
 193  fun5_3    2016 non-null   float64
 194  amb5_3    2016 non-null   float64
dtypes: float64(174), int64(13), object(8)
memory usage: 12.5+ MB
None

In [ ]:
df_cleaned.loc[1755,:]

iid                 122
id                  1.0
gender                1
idg                   2
condtn                1
wave                  5
round                10
position              4
positin1            NaN
order                 6
partner               7
pid                 NaN
match                 0
int_corr          -0.12
samerace              0
age_o               NaN
race_o              NaN
pf_o_att            NaN
pf_o_sin            NaN
pf_o_int            NaN
pf_o_fun            NaN
pf_o_amb            NaN
pf_o_sha            NaN
dec_o                 0
attr_o              NaN
sinc_o              NaN
intel_o             NaN
fun_o               NaN
amb_o               NaN
shar_o              NaN
like_o              NaN
prob_o              NaN
met_o               NaN
age                22.0
field               Law
field_cd            1.0
undergra            NaN
mn_sat              NaN
tuition             NaN
race                6.0
imprace             1.0
imprelig            1.0
from        Long Island
zipcode          11,793
income        57,887.00
goal                1.0
date                3.0
go_out              1.0
career           Lawyer
career_c            1.0
sports              7.0
tvsports            9.0
exercise            7.0
dining              9.0
museums             7.0
art                 6.0
hiking              5.0
gaming              6.0
clubbing            6.0
reading             6.0
tv                  8.0
theater             7.0
movies              8.0
concerts            8.0
music               8.0
shopping            5.0
yoga                4.0
exphappy            6.0
expnum             10.0
attr1_1            40.0
sinc1_1            15.0
intel1_1           10.0
fun1_1             20.0
amb1_1              5.0
shar1_1            10.0
attr4_1             NaN
sinc4_1             NaN
intel4_1            NaN
fun4_1              NaN
amb4_1              NaN
shar4_1             NaN
attr2_1            50.0
sinc2_1            10.0
intel2_1           10.0
fun2_1             10.0
amb2_1             10.0
shar2_1            10.0
attr3_1             7.0
sinc3_1            10.0
fun3_1              8.0
intel3_1            8.0
amb3_1              8.0
attr5_1             NaN
sinc5_1             NaN
intel5_1            NaN
fun5_1              NaN
amb5_1              NaN
dec                   0
attr                6.0
sinc               10.0
intel               8.0
fun                 8.0
amb                 8.0
shar                8.0
like                8.0
prob                4.0
met                 2.0
match_es            4.0
attr1_s             NaN
sinc1_s             NaN
intel1_s            NaN
fun1_s              NaN
amb1_s              NaN
shar1_s             NaN
attr3_s             NaN
sinc3_s             NaN
intel3_s            NaN
fun3_s              NaN
amb3_s              NaN
satis_2             5.0
length              3.0
numdat_2            3.0
attr7_2             NaN
sinc7_2             NaN
intel7_2            NaN
fun7_2              NaN
amb7_2              NaN
shar7_2             NaN
attr1_2            50.0
sinc1_2            10.0
intel1_2           10.0
fun1_2             10.0
amb1_2             10.0
shar1_2            10.0
attr4_2             NaN
sinc4_2             NaN
intel4_2            NaN
fun4_2              NaN
amb4_2              NaN
shar4_2             NaN
attr2_2             NaN
sinc2_2             NaN
intel2_2            NaN
fun2_2              NaN
amb2_2              NaN
shar2_2             NaN
attr3_2             8.0
sinc3_2            10.0
intel3_2            8.0
fun3_2              8.0
amb3_2              8.0
attr5_2             NaN
sinc5_2             NaN
intel5_2            NaN
fun5_2              NaN
amb5_2              NaN
you_call            1.0
them_cal            0.0
date_3              1.0
numdat_3            NaN
num_in_3            NaN
attr1_3            50.0
sinc1_3            10.0
intel1_3           10.0
fun1_3             10.0
amb1_3             10.0
shar1_3            10.0
attr7_3             NaN
sinc7_3             NaN
intel7_3            NaN
fun7_3              NaN
amb7_3              NaN
shar7_3             NaN
attr4_3             NaN
sinc4_3             NaN
intel4_3            NaN
fun4_3              NaN
amb4_3              NaN
shar4_3             NaN
attr2_3             NaN
sinc2_3             NaN
intel2_3            NaN
fun2_3              NaN
amb2_3              NaN
shar2_3             NaN
attr3_3             8.0
sinc3_3            10.0
intel3_3            8.0
fun3_3              8.0
amb3_3              8.0
attr5_3             NaN
sinc5_3             NaN
intel5_3            NaN
fun5_3              NaN
amb5_3              NaN
Name: 1755, dtype: object

In [ ]:
preferences = df.groupby("gender")[['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1']].mean()
preferences.index = ["Female (Rating Men)", "Male (Rating Women)"]
preferences_transposed = preferences.T

preferences_transposed.head()

          Female (Rating Men)  Male (Rating Women)
attr1_1             18.055224            26.921689
sinc1_1             18.305008            16.498436
intel1_1            21.002502            19.537374
fun1_1              17.147292            17.763893
amb1_1              12.827222             8.552829

In [ ]:
fig = px.box(df, x=['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1'], color='gender')
fig.show()

In [ ]:
fig = px.histogram(
    df,
    x="gender",
    y=['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1'],
    barmode='group',
    histfunc='avg',
)
fig.update_layout(xaxis_title="Gender", yaxis_title="Average Score by Attribute", legend_title_text="Attributes")
fig.show()

In [ ]:
import plotly.graph_objects as go

# Define the time periods and their corresponding columns
time_periods = {
    "Pre-Event": ['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1'],
    "During Event": ['attr1_s','sinc1_s','intel1_s','fun1_s','amb1_s', 'shar1_s'],
    "Day After": ['attr1_2','sinc1_2','intel1_2','fun1_2','amb1_2', 'shar1_2'],
    "3-4 Weeks Later": ['attr1_3','sinc1_3','intel1_3','fun1_3','amb1_3', 'shar1_3']
}

# The list of attribute names (for the legend)
attributes = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Shared Interests']

fig = go.Figure()

# 1. Create Traces
# We need 6 traces (one per attribute) for EACH time period. Total = 24 traces.
# Only the first 6 (Pre-Event) will be visible initially.
for label, columns in time_periods.items():
    is_visible = (label == "Pre-Event")
    for i, col in enumerate(columns):
        fig.add_trace(
            go.Histogram(
                x=df["gender"],
                y=df[col],
                name=attributes[i], # Legend name
                histfunc='avg',
                visible=is_visible,
                marker_color=px.colors.qualitative.Plotly[i] # Keep colors consistent
            )
        )

# 2. Create Buttons
# Each button needs to turn ON 6 specific traces and look OFF the other 18.
buttons = []
num_attributes = 6
total_traces = len(time_periods) * num_attributes

for i, label in enumerate(time_periods.keys()):
    # Create a "visibility" list [False, False, ..., True, True, True, True, True, True, ..., False]
    visibility = [False] * total_traces
    
    # Calculate the range of indices for this time period
    start_idx = i * num_attributes
    end_idx = start_idx + num_attributes
    
    # Set the 6 relevant traces to True
    visibility[start_idx:end_idx] = [True] * num_attributes
    
    buttons.append(dict(
        label=label,
        method="update",
        args=[{"visible": visibility}]
    ))

# 3. Update Layout
fig.update_layout(
    updatemenus=[dict(active=0, buttons=buttons)],
    title="Average Attribute Scores by Time Period",
    barmode='group',
    xaxis_title="Gender",
    yaxis_title="Average Score"
)

fig.show()

In [ ]:
### To detail more with the time frame
#----------------
# The least desirable attributes in male partner is "Shared Interests", followed really closely by "Ambitious"
# The least desirable attributes in female partner is "Ambitious", followed by "Shared Interests".
# For male partner the two least desirable attributes are almost identicals. On the other hand, for the female partner there is a clear least favorite attribute demarked.

In [ ]:
fig = px.histogram(
    df,
    x="gender",
    y=['attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1', 'shar2_1'],
    barmode='group',
    histfunc='avg',
)
fig.update_layout(xaxis_title="Gender", yaxis_title="Average Score by Attribute", legend_title_text="Attributes")
fig.show()

In [ ]:
import plotly.graph_objects as go

# Define the time periods and their corresponding columns
time_periods = {
    "Pre-Event": ['attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1', 'shar2_1'],
    "Day After": ['attr2_2','sinc2_2','intel2_2','fun2_2','amb2_2', 'shar2_2'],
    "3-4 Weeks Later": ['attr2_3','sinc2_3','intel2_3','fun2_3','amb2_3', 'shar2_3']
}

# The list of attribute names (for the legend)
attributes = ['Attractive', 'Sincere', 'Intelligent', 'Fun', 'Ambitious', 'Shared Interests']

fig = go.Figure()

# 1. Create Traces
# We need 6 traces (one per attribute) for EACH time period. Total = 24 traces.
# Only the first 6 (Pre-Event) will be visible initially.
for label, columns in time_periods.items():
    is_visible = (label == "Pre-Event")
    for i, col in enumerate(columns):
        fig.add_trace(
            go.Histogram(
                x=df["gender"],
                y=df[col],
                name=attributes[i], # Legend name
                histfunc='avg',
                visible=is_visible,
                marker_color=px.colors.qualitative.Plotly[i] # Keep colors consistent
            )
        )

# 2. Create Buttons
# Each button needs to turn ON 6 specific traces and look OFF the other 18.
buttons = []
num_attributes = 6
total_traces = len(time_periods) * num_attributes

for i, label in enumerate(time_periods.keys()):
    # Create a "visibility" list [False, False, ..., True, True, True, True, True, True, ..., False]
    visibility = [False] * total_traces
    
    # Calculate the range of indices for this time period
    start_idx = i * num_attributes
    end_idx = start_idx + num_attributes
    
    # Set the 6 relevant traces to True
    visibility[start_idx:end_idx] = [True] * num_attributes
    
    buttons.append(dict(
        label=label,
        method="update",
        args=[{"visible": visibility}]
    ))

# 3. Update Layout
fig.update_layout(
    updatemenus=[dict(active=0, buttons=buttons)],
    title="Average Attribute Scores by Time Period",
    barmode='group',
    xaxis_title="Gender",
    yaxis_title="Average Score"
)

fig.show()

In [ ]:
# 1. Melt the data for both sets of columns
long_df = df.melt(
    id_vars=['gender'], 
    value_vars=['attr1_1','sinc1_1','intel1_1','fun1_1','amb1_1', 'shar1_1',
                'attr2_1','sinc2_1','intel2_1','fun2_1','amb2_1', 'shar2_1'],
    var_name='Attribute_Full', 
    value_name='Score'
)

print(long_df)

# 2. Extract the "Type" (1_1 vs 2_1) and "Attribute Name"
#   'attr1_1' -> Attribute='attr', Type='What I want'
long_df['Type'] = long_df['Attribute_Full'].apply(lambda x: 'What I want' if '1_1' in x else 'What others want')
long_df['Attribute'] = long_df['Attribute_Full'].str[:4] # Grab first 4 chars (attr, sinc, etc)

# 3. Plot with Facets
fig = px.histogram(
    long_df, 
    x="gender", 
    y="Score", 
    color="Attribute",      # Colors will now match across both panels
    facet_col="Type",       # Creates the side-by-side split!
    barmode="group",
    histfunc="avg"
)

fig.update_layout(yaxis_title="Average Score")
fig.show()

        gender Attribute_Full  Score
0            0        attr1_1   15.0
1            0        attr1_1   15.0
2            0        attr1_1   15.0
3            0        attr1_1   15.0
4            0        attr1_1   15.0
...        ...            ...    ...
100531       1        shar2_1   20.0
100532       1        shar2_1   20.0
100533       1        shar2_1   20.0
100534       1        shar2_1   20.0
100535       1        shar2_1   20.0

[100536 rows x 3 columns]

In [ ]:
# The females were expecting from male partners to look for the "Attractiveness" as top Attributes, and they were right.
# At the opposite, the males were expecting from the female partners to look for the "Attractiveness" as top Attributes, ad they were wrong because they are looking "Intelligent" partners.

In [ ]:
print(df[df["gender"] == 0]["imprace"].value_counts())
print(df[df["gender"] == 1]["imprace"].value_counts())
print(df[df["gender"] == 0]["imprace"].mean())
print(df[df["gender"] == 1]["imprace"].mean())

imprace
1.0     1189
2.0      563
3.0      450
8.0      426
5.0      351
9.0      294
4.0      276
6.0      208
10.0     201
7.0      159
0.0        8
Name: count, dtype: int64
imprace
1.0     1609
3.0      533
2.0      391
7.0      384
6.0      316
5.0      306
8.0      237
4.0      234
9.0      115
10.0      49
Name: count, dtype: int64
4.108848484848485
3.464542405366555

In [ ]:
from sklearn.preprocessing import StandardScaler

# 1. Filter out Waves 6-9 (where they used a 1-10 scale for shared interests)
# We only want the waves where they used the 100-point allocation method.
df_clean = df[~df['wave'].isin([6, 7, 8, 9])].copy()
# Drop rows where either value is missing to keep the comparison fair
df_clean = df_clean.dropna(subset=['shar1_1', 'imprace'])

# 2. Initialize the Scaler
scaler = StandardScaler()

# 3. Compute Z-Scores for both columns
# This transforms them to the same scale (Mean = 0, Std Dev = 1)
df_clean[['z_shared_interest', 'z_race_importance']] = scaler.fit_transform(df_clean[['shar1_1', 'imprace']])

# 4. Melt the data for plotting
df_melted_z = df_clean.melt(
    value_vars=['z_shared_interest', 'z_race_importance'], 
    var_name='Attribute', 
    value_name='Z-Score'
)

# Rename for nicer labels in the plot
df_melted_z['Attribute'] = df_melted_z['Attribute'].map({
    'z_shared_interest': 'Shared Interests', 
    'z_race_importance': 'Same Racial Background'
})

# 5. Visualize
fig = px.box(
    df_melted_z, 
    x='Attribute', 
    y='Z-Score', 
    title="Relative Importance: Shared Interests vs. Race (Standardized)",
    color='Attribute',
    points="outliers" # Only show outliers to keep it clean, or "all" to see distribution
)

# Add a zero line to show the average
fig.add_hline(y=0, line_dash="dash", annotation_text="Average Importance")

fig.show()

print("Average Z-Score for Shared Interests:", df_clean['z_shared_interest'].mean())
print("Average Z-Score for Race Importance:", df_clean['z_race_importance'].mean())

Average Z-Score for Shared Interests: -6.363069275463584e-17
Average Z-Score for Race Importance: -8.271990058102659e-17

In [ ]:
# We see that people care more about Racial Background than Shared Interests.

In [ ]:
df.head()
# attr_o	sinc_o	intel_o	fun_o	amb_o	shar_o  (Partner rating)
# attr3_1   sinc3_1 int3_1  fun3_1  amb3_1  shar3_1 (Self rating)

# if attribute_3_1 - attribute_o = 0 -> Accurate
# if attribute_3_1 - attribute_o > 0 -> Overestimated
# if attribute_3_1 - attribute_o < 0 -> Underestimated
# Group by id to have the accuracy rating of each person

,iid,id,gender,idg,condtn,wave,round,position,positin1,order,partner,pid,match,int_corr,samerace,age_o,race_o,pf_o_att,pf_o_sin,pf_o_int,pf_o_fun,pf_o_amb,pf_o_sha,dec_o,attr_o,sinc_o,intel_o,fun_o,amb_o,shar_o,like_o,prob_o,met_o,age,field,field_cd,undergra,mn_sat,tuition,race,imprace,imprelig,from,zipcode,income,goal,date,go_out,career,career_c,sports,tvsports,exercise,dining,museums,art,hiking,gaming,clubbing,reading,tv,theater,movies,concerts,music,shopping,yoga,exphappy,expnum,attr1_1,sinc1_1,intel1_1,fun1_1,amb1_1,shar1_1,attr4_1,sinc4_1,intel4_1,fun4_1,amb4_1,shar4_1,attr2_1,sinc2_1,intel2_1,fun2_1,amb2_1,shar2_1,attr3_1,sinc3_1,fun3_1,intel3_1,amb3_1,attr5_1,sinc5_1,intel5_1,fun5_1,amb5_1,dec,attr,sinc,intel,fun,amb,shar,like,prob,met,match_es,attr1_s,sinc1_s,intel1_s,fun1_s,amb1_s,shar1_s,attr3_s,sinc3_s,intel3_s,fun3_s,amb3_s,satis_2,length,numdat_2,attr7_2,sinc7_2,intel7_2,fun7_2,amb7_2,shar7_2,attr1_2,sinc1_2,intel1_2,fun1_2,amb1_2,shar1_2,attr4_2,sinc4_2,intel4_2,fun4_2,amb4_2,shar4_2,attr2_2,sinc2_2,intel2_2,fun2_2,amb2_2,shar2_2,attr3_2,sinc3_2,intel3_2,fun3_2,amb3_2,attr5_2,sinc5_2,intel5_2,fun5_2,amb5_2,you_call,them_cal,date_3,numdat_3,num_in_3,attr1_3,sinc1_3,intel1_3,fun1_3,amb1_3,shar1_3,attr7_3,sinc7_3,intel7_3,fun7_3,amb7_3,shar7_3,attr4_3,sinc4_3,intel4_3,fun4_3,amb4_3,shar4_3,attr2_3,sinc2_3,intel2_3,fun2_3,amb2_3,shar2_3,attr3_3,sinc3_3,intel3_3,fun3_3,amb3_3,attr5_3,sinc5_3,intel5_3,fun5_3,amb5_3
0,1,1.0,0,1,1,1,10,7,NaN,4,1,11.0,0,0.14,0,27.0,2.0,35.0,20.0,20.0,20.0,0.0,5.0,0,6.0,8.0,8.0,8.0,8.0,6.0,7.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,6.0,9.0,7.0,7.0,6.0,5.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
1,1,1.0,0,1,1,1,10,7,NaN,3,2,12.0,0,0.54,0,22.0,2.0,60.0,0.0,0.0,40.0,0.0,0.0,0,7.0,8.0,10.0,7.0,7.0,5.0,8.0,4.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,8.0,7.0,8.0,5.0,6.0,7.0,5.0,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
2,1,1.0,0,1,1,1,10,7,NaN,10,3,13.0,1,0.16,1,22.0,4.0,19.0,18.0,19.0,18.0,14.0,12.0,1,10.0,10.0,10.0,10.0,10.0,10.0,10.0,10.0,1.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,8.0,9.0,8.0,5.0,7.0,7.0,NaN,1.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
3,1,1.0,0,1,1,1,10,7,NaN,5,4,14.0,1,0.61,0,23.0,2.0,30.0,5.0,15.0,40.0,5.0,5.0,1,7.0,8.0,9.0,8.0,9.0,8.0,7.0,7.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,7.0,6.0,8.0,7.0,6.0,8.0,7.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN
4,1,1.0,0,1,1,1,10,7,NaN,7,5,15.0,1,0.21,0,24.0,3.0,30.0,10.0,20.0,10.0,10.0,20.0,1,8.0,7.0,9.0,6.0,9.0,7.0,8.0,6.0,2.0,21.0,Law,1.0,NaN,NaN,NaN,4.0,2.0,4.0,Chicago,"60,521","69,487.00",2.0,7.0,1.0,lawyer,NaN,9.0,2.0,8.0,9.0,1.0,1.0,5.0,1.0,5.0,6.0,9.0,1.0,10.0,10.0,9.0,8.0,1.0,3.0,2.0,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,35.0,20.0,15.0,20.0,5.0,5.0,6.0,8.0,8.0,8.0,7.0,NaN,NaN,NaN,NaN,NaN,1,5.0,6.0,7.0,7.0,6.0,6.0,6.0,6.0,2.0,4.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,2.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,19.44,16.67,13.89,22.22,11.11,16.67,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6.0,7.0,8.0,7.0,6.0,NaN,NaN,NaN,NaN,NaN,1.0,1.0,0.0,NaN,NaN,15.0,20.0,20.0,15.0,15.0,15.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,7.0,7.0,7.0,7.0,NaN,NaN,NaN,NaN,NaN

In [ ]:
df_short = df[["iid", "gender", "pid", "attr_o", "attr3_1", "sinc_o", "sinc3_1", "intel_o", "intel3_1", "fun_o", "fun3_1", "amb_o", "amb3_1"]]
df_short.isnull().index.tolist()
df_short.info()
#df_short['attr_diff'] = df_short['attr3_1'] - df_short['attr_o']
#df_short['sinc_diff'] = df_short['sinc3_1'] - df_short['sinc_o']
#df_short['intel_diff'] = df_short['intel3_1'] - df_short['intel_o']
#df_short['fun_diff'] = df_short['fun3_1'] - df_short['fun_o']
#df_short['amb_diff'] = df_short['amb3_1'] - df_short['amb_o']
#df_short.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8378 entries, 0 to 8377
Data columns (total 13 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   iid       8378 non-null   int64
 1   gender    8378 non-null   int64
 2   pid       8368 non-null   float64
 3   attr_o    8166 non-null   float64
 4   attr3_1   8273 non-null   float64
 5   sinc_o    8091 non-null   float64
 6   sinc3_1   8273 non-null   float64
 7   intel_o   8072 non-null   float64
 8   intel3_1  8273 non-null   float64
 9   fun_o     8018 non-null   float64
 10  fun3_1    8273 non-null   float64
 11  amb_o     7656 non-null   float64
 12  amb3_1    8273 non-null   float64
dtypes: float64(11), int64(2)
memory usage: 851.0 KB

In [ ]:
df_short.loc[1755,:]

iid         122.0
gender        1.0
pid           NaN
attr_o        NaN
attr3_1       7.0
sinc_o        NaN
sinc3_1      10.0
intel_o       NaN
intel3_1      8.0
fun_o         NaN
fun3_1        8.0
amb_o         NaN
amb3_1        8.0
Name: 1755, dtype: float64